<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return [
    'version'     => '2026.03.06',
    'data_date'   => '2026-03-06',
    'source_hash' => '90f900873a13a3277f95639cc4a5d860004285d5',
    'generated_at' => '2026-03-06T22:52:43+00:00',
    'source'      => [
        'repo' => 'cahyadsn/wilayah_boundaries',
        'branch' => 'main',
        'hash' => '90f900873a13a3277f95639cc4a5d860004285d5',
    ],
    'total'       => 4414,
];
