<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return array (
  'version' => '2026.05.13',
  'data_date' => '2026-05-13',
  'source_hash' => 'a386adb9ae54245935b2ef2c8351e14a74852cad',
  'generated_at' => '2026-05-13T06:40:04+00:00',
  'source' => 
  array (
    'repo' => 'cahyadsn/wilayah_boundaries',
    'branch' => 'main',
    'hash' => 'a386adb9ae54245935b2ef2c8351e14a74852cad',
  ),
  'asset' => 
  array (
    'name' => 'boundaries-dataset-v1.0.8.ndjson.gz',
    'url' => 'https://github.com/aliziodev/laravel-wilayah-boundaries/releases/download/v1.0.8/boundaries-dataset-v1.0.8.ndjson.gz',
    'format' => 'ndjson.gz',
    'size_bytes' => 104707892,
  ),
  'counts' => 
  array (
    'prov' => 38,
    'kab' => 514,
    'kec' => 7265,
    'kel' => 82987,
    'total' => 90804,
  ),
);
