<?php

// Auto-generated by CI/CD. DO NOT EDIT.
return [
    'version' => '2026.03.07',
    'data_date' => '2026-03-07',
    'source_hash' => '90f900873a13a3277f95639cc4a5d860004285d5',
    'generated_at' => '2026-03-07T00:07:36+00:00',
    'source' => [
        'repo' => 'cahyadsn/wilayah_boundaries',
        'branch' => 'main',
        'hash' => '90f900873a13a3277f95639cc4a5d860004285d5',
    ],
    'asset' => [
        'name' => 'boundaries-dataset-v1.0.4.ndjson.gz',
        'url' => 'https://github.com/aliziodev/laravel-wilayah-boundaries/releases/download/v1.0.4/boundaries-dataset-v1.0.4.ndjson.gz',
        'format' => 'ndjson.gz',
        'size_bytes' => 104710948,
    ],
    'counts' => [
        'prov' => 38,
        'kab' => 514,
        'kec' => 7265,
        'kel' => 82987,
        'total' => 90804,
    ],
];
