<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return [
    'version' => '2026.03.06',
    'data_date' => '2026-03-06',
    'source_hash' => 'unknown',
    'generated_at' => '2026-03-06T23:35:24+00:00',
    'source' => [
        'repo' => 'cahyadsn/wilayah_boundaries',
        'branch' => 'main',
        'hash' => 'unknown',
    ],
    'asset' => [
        'name' => 'boundaries-dataset.ndjson.gz',
        'url' => '',
        'format' => 'ndjson.gz',
        'size_bytes' => 104710948,
    ],
    'counts' => [
        'prov' => 38,
        'kab' => 514,
        'kec' => 7265,
        'kel' => 82987,
        'total' => 90804,
    ],
];
